## Generated by Migo's make.py
rm=/bin/rm -f
CC= g++
PROGNAME= neatm
CFLAGS= -O3
SRCS = main.cpp neatm.cpp neatm_input_file.cpp integral.cpp 
OBJS = main.o neatm.o neatm_input_file.o integral.o 

.cpp.o:
	$(CC) -c $(CFLAGS) $< -o $@

all: $(SRCS) $(PROGNAME)

$(PROGNAME) : $(OBJS)
	$(CC) $(CFLAGS) -o $(PROGNAME) $(OBJS)

clean:
	$(rm) $(OBJS) $(PROGNAME) core *~
